#!/bin/bash
set -ex

# Format the code
black *.py

# This script loads in the XPP using the parser in pyNeuroML, and converts the channels to NeuroML
# It will also run a test simulation of the cells and save the results
# NOTE: make sure to update to a recent version of pyNeuroML!
python GenerateNeuroML.py -jnml

# This will use the generated NeuroML cells and create networks with a number of (unconnected cells) and 
# inject current steps into them to replicate the currnt clamp protocols in Figs 4C and 7B in the paper
python GenerateExamples.py -jnml

# This will load the original XPP using pyNeuroML, run it, save the results and plot them against the 
# results generated by the NeuroML in GenerateNeuroML.py
python TestXPP.py

omv all -V 

